notification:
  slack_channel: team-need4speed-auto
  
release:
  workflow:
    path: github.com/AppDirect/cd-workflows//bluegreen-release.yaml?ref=master
  triggers:
    - filter: ^v\d+\.\d+\.\d+$
      parameters:
        - name: deploy-only-test-repos
          value: |
            [
              "manifests-shared.test.us-east-1",
              "manifests-azr.test.shared.use1"
            ]
        - name: deploy-only-repos
          value: |
            []
